// React without WCAG/src/components/AuctionList.jsx
import {React, useState, useEffect} from 'react';
import {useParams} from "react-router-dom";
import Navbar from './Navbar';
import { getAuctionByCategory, getAuctionBySearch, getBoughtAuction } from "../api/AuctionAPI";
import './AuctionList.css';

function AuctionList() {
  const { category } = useParams();
  const { search } = useParams();
  const { id } = useParams();
  const [auctions, setAuctions] = useState();

  useEffect(() => {
    async function getAuctions() {
      try {
        let auctionList;
        if (category !== undefined)
          auctionList = await getAuctionByCategory(category);
        if (search !== undefined)
          auctionList = await getAuctionBySearch(search);
        if (id !== undefined)
          auctionList = await getBoughtAuction(id);

        setAuctions(auctionList);
      }
      catch { }
    }
    
    getAuctions();
  }, [category, search, id]);

  
  function auctionClick(props) {
    if(window.confirm("Do you want to be redirected to auction page?"))
      document.location.href = "/auction/" + props.id;
  }

  function closeAlert() {
    document.getElementById('alert').style.display='none';
  }

  function AuctionPanel(props) {
    const endDate = new Date(props.auction.endDate);
    return  <div className="auctionListPanel" onClick={() => auctionClick(props.auction)}>
              <div className="auctionListImageComponent">
                <img className="auctionListImg" src={props.auction.image}/>
                <label className="auctionListTitleLabel"><b>{props.auction.title}</b></label>
              </div>
              <div className="auctionListTextComponent" >
                <label><b>Price: {props.auction.price} PLN</b></label>
                <label><b>Ends on: {endDate.toLocaleString()}</b></label>
              </div>
            </div>
  }

  return (
    <div>
      <Navbar/>
        {auctions && auctions.map((auction) =>
          <div className="auctionListContainer">
            <span id='alert' className="auctionListAlert" onClick={closeAlert}>
              Number of auctions found: {auctions.length}.
            </span>
            <AuctionPanel key={auction.id} auction={auction}/>
          </div>
        )}
    </div>
  );
}

export default AuctionList;

// Vue without WCAG/src/components/AuctionList.vue
<template>
<div>
  <div v-if="auctionList" class="auctionListContainer">
    <span id='alert' class="auctionListAlert" @click="closeAlert">
      Number of auctions found: {{auctionList.length}}.
    </span>
    <div v-for="auction of auctionList" :key="auction" class="auctionListPanel" @click="auctionClick(auction)">
      <div class="auctionListImageComponent">
        <img class="auctionListImg" v-bind:src="auction.image"/>
        <label class="auctionListTitleLabel"><b>{{auction.title}}</b></label>
      </div>
      <div class="auctionListTextComponent" >
        <label><b>Price: {{auction.price}} PLN</b></label>
        <label><b>{{getAuctionDate(auction.endDate)}}</b></label>
      </div>
    </div>
  </div>
</div>
</template>

<script>
import { getAuctionByCategory, getAuctionBySearch, getBoughtAuction } from "../api/auctionAPIService";

export default {
  name: 'AuctionListComponent',

  data() {
    return { 
      auctionList: [],
    }
  },

  created() {
    try {
      this.getAuctions();
    }
    catch(error) {
      console.log(error);
    }
  },

  methods: {
    async getAuctions() {
      try{
        if (this.$route.params.category != null) {
          this.auctionList = await getAuctionByCategory(this.$route.params.category);
        }
        if (this.$route.params.search != null) {
          this.auctionList = await getAuctionBySearch(this.$route.params.search);
        }
        if (this.$route.params.id != null)
          this.auctionList = await getBoughtAuction(this.$route.params.id);
      }
      catch(error) {
        console.log(error);
      }
    },

    auctionClick(props) {
      if(window.confirm("Do you want to be redirected to auction page?")) {
        document.location.href = "/auction/" + props.id;
      }
    },

    closeAlert() {
      document.getElementById('alert').style.display='none';
    },

    getAuctionDate(dateString) {
      let date = new Date(dateString);
      return date.toLocaleString();
    }
  }
}
</script>

<style scoped>
.auctionListContainer {
    display: flex;
    flex-direction: column;
    align-items: center;
}

.auctionListPanel { 
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
    padding-left: 5vw;
    padding-right: 5vw;
    margin-top: 3vh;
    margin-left: 3vw;
    margin-right: 3vw;
    border-style: solid;
    width: 90%;
    background-color: antiquewhite;
    height: 20vh;
    cursor: pointer;
}

.auctionListImg { 
    height: 18vh;
    width: 18vh;
    border-radius: 50%;
    border: 10px;
}

.auctionListTitleLabel { 
    margin-left: 20px;
}

.auctionListTextComponent { 
    display: flex;
    flex-direction: column;
    align-items: flex-end;
    justify-content: space-between;
    height: 100%;
    padding-top: 5vh;
    padding-bottom: 5vh;
}

.auctionListAlert {
    margin-top: 1%;
    background-color: yellow;
    color: black;
    width: 90%;
    cursor: pointer;
    height: 4vh;
    text-align: center;
    font-size: large;
}
</style>
