// Angular without WCAG/src/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { LocalService } from '../local.service';
import { UserAPIService } from '../../api/user-api.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  username: string = "";
  password: string = "";
  isLoading: boolean = false;
  registerError: string = "";
  checkboxState: boolean = false;

  constructor(private localService: LocalService, private userAPIService: UserAPIService) { }

  ngOnInit(): void {
  }

  async onLoginClicked(): Promise<void> {
    try {
      this.isLoading = true;
      this.registerError = "";
      if (this.username == "" || this.password == "") {
        return;
      }
      
      const loginParams = {
        Login: this.username,
        Password: this.password
      };
      const userParameters = await this.userAPIService.userLogin(loginParams);
      this.localService.setStorage("user", userParameters);      
      document.location.href = "/";
    } catch {
    } finally {
      this.isLoading = false;
    }
  }
}

<div>
  <form class='loginContainer' (ngSubmit)='onLoginClicked()'>
    <img src="assets/login.jpg"/>
    <div id='usernameDiv' class='loginLabel' contenteditable="true" name="username" [(ngModel)]="username">Username</div>
    <label class='loginLabel'><b>Password:</b></label>
    <input class='loginInput' name="password" [(ngModel)]="password" placeholder='password' type="password" />
    <input class='loginSubmit' type="submit" value="Submit" />
    <a accesskey="q" class='loginHyperlink' href="/register">Click to create account</a>
    <p *ngIf="isLoading">Logging user....</p>
    <p *ngIf="registerError != ''">{{registerError}}</p>
  </form>
</div>

// React without WCAG/src/components/Login.jsx
import {React, useState} from "react";
import Navbar from './Navbar';
import { userLogin } from "../api/UserAPI";
import './Login.css';
import { setStorage } from "../utils/localStorage";

function Login() {
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [loginError, setLoginError] = useState('');

  async function onLoginClicked(e) {
    e.preventDefault();
    const username = document.getElementById('usernameDiv').innerHTML;
    if (!username || !password) {
      return;
    }
    setIsLoading(true);
    setLoginError('');
    try {
      const loginParams = {
        Login: username,
        Password: password
      };
      const userParameters = await userLogin(loginParams);
      setStorage("user", userParameters);
      document.location.href = "/";
    } catch {
    } finally {
      setIsLoading(false);
    }
  }

  function onPasswordChanged(event) {
    setPassword(event.target.value);
  }

  return (
    <div>
      <Navbar />
      <form className='loginContainer' onSubmit={onLoginClicked}>
        <img src={require('../img/login.jpg')} />
        <div id='usernameDiv' className='loginLabel' contentEditable={true}>Username</div>
        <label className='loginLabel'><b>Password:</b></label>
        <input className='loginInput' placeholder='password' type="password" onChange={onPasswordChanged} required />
        <input className='loginSubmit' type="submit" value="Submit" />
        <a accessKey="q" className='loginHyperlink' href="/register">Click to create account</a>
        {isLoading && <p>Logging in....</p>}
        {loginError && <p>{loginError}</p>}
      </form>
    </div>
  );
}

export default Login;
