// Vue without WCAG/src/components/Review.vue
<template>
<div>
  <div class='reviewContainer'>
    <label id='videoLabel' class='reviewLabel' @click="handleAnimation"><b>Watch review, click label to animate background:</b></label>
    <video controls class='mediaElement'>
      <source src="@/assets/video.mp4" type="video/mp4" />
    </video>
    <label class='reviewLabel' @click="handleAnimation"><b>Listen to expert opinion about it:</b></label>
    <audio autoplay="autoplay" class='mediaElement'>
      <source src="@/assets/audio.mp3" type="audio/mpeg" />
    </audio>
    <button class='goBackButton' @click="onGoBackClick"></button>
  </div>
</div>
</template>

<script>
export default {
  name: 'ReviewComponent',

  created(){
    setTimeout(this.goBackTimeout, 60000);
  },

  methods: {
    onGoBackClick() {
      history.back();
    },

    handleAnimation() {
      document.getElementById('videoLabel').style.animationIterationCount = 'infinite';
    },

    goBackTimeout() {
      window.history.back();
    }
  }
}
</script>

<style scoped>
.reviewContainer {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}

.mediaElement {
    width: 70%;
}

.goBackButton { 
    background-color: red;
    border-radius: 15px;
    width: 20px;
    height: 20px;
}

.reviewLabelAudio {
    margin-top: 2%;
    font-size: x-large;
}

.reviewLabelVideo {
    margin-top: 2%;
    font-size: x-large;
    background-color: green;
    animation-name: homeTitleAnimation;
    animation-duration: 1s;
    animation-iteration-count: 0;
}

@keyframes example {
    0%   {background-color: green;}
    50%  {background-color: blue;}
}
</style>

// React without WCAG/src/components/Review.jsx
import { React, useEffect } from 'react';
import Navbar from './Navbar'
import './Review.css';

function Review() {
  useEffect(() => {
    setTimeout(function () { onGoBackClick(); }, 30000);
  }, []);

  function onGoBackClick() {
    window.history.back();
  }

  function handleAnimation() {
    document.getElementById('videoLabel').style = 'animation-iteration-count: infinite;';
  }

  return (
    <div>
      <Navbar />
      <div className='reviewContainer'>
        <label id='videoLabel' className='reviewLabelVideo' onClick={handleAnimation}><b>Watch review, click label to animate background:</b></label>
        <video controls className='mediaElement'>
          <source src={require('../media/video.mp4')} type="video/mp4" />
        </video>
        <label className='reviewLabelAudio' onClick={handleAnimation}><b>Listen to expert opinion about it:</b></label>
        <audio autoPlay="autoplay" className='mediaElement'>
          <source src={require('../media/audio.mp3')} type="audio/mpeg" />
        </audio>
        <button className='goBackButton' onClick={onGoBackClick}></button>
      </div>
    </div>
  );
}

export default Review;
