// Angular without WCAG/src/components/review/review.component.ts
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';

@Component({
  selector: 'app-review',
  templateUrl: './review.component.html',
  styleUrls: ['./review.component.css']
})
export class ReviewComponent implements OnInit {
  timeoutId : number | undefined;

  constructor(private location: Location) { }

  ngOnInit(): void {
    this.timeoutId = window.setTimeout(this.onGoBackClick, 30000);
  }

  onGoBackClick(): void {
    this.location.back();
  }

  handleAnimation(): void {
    (document.getElementById('videoLabel') as HTMLElement).style.animationIterationCount = 'infinite';
  }
}

<div>
  <div class='reviewContainer'>
    <label id='videoLabel' class='reviewLabel' (click)="handleAnimation()"><b>Watch review, click label to animate background:</b></label>
    <video controls class='mediaElement'>
      <source src="assets/video.mp4" type="video/mp4" />
    </video>
    <label class='reviewLabel' (click)="handleAnimation()"><b>Listen to expert opinion about it:</b></label>
    <audio autoplay="autoplay" class='mediaElement'>
      <source src="assets/audio.mp3" type="audio/mpeg" />
    </audio>
    <button class='goBackButton' (click)="onGoBackClick()"></button>
  </div>
</div>

// React without WCAG/src/components/Review.jsx
import { React, useEffect } from 'react';
import Navbar from './Navbar'
import './Review.css';

function Review() {
  useEffect(() => {
    setTimeout(function () { onGoBackClick(); }, 30000);
  }, []);

  function onGoBackClick() {
    window.history.back();
  }

  function handleAnimation() {
    document.getElementById('videoLabel').style = 'animation-iteration-count: infinite;';
  }

  return (
    <div>
      <Navbar />
      <div className='reviewContainer'>
        <label id='videoLabel' className='reviewLabelVideo' onClick={handleAnimation}><b>Watch review, click label to animate background:</b></label>
        <video controls className='mediaElement'>
          <source src={require('../media/video.mp4')} type="video/mp4" />
        </video>
        <label className='reviewLabelAudio' onClick={handleAnimation}><b>Listen to expert opinion about it:</b></label>
        <audio autoPlay="autoplay" className='mediaElement'>
          <source src={require('../media/audio.mp3')} type="audio/mpeg" />
        </audio>
        <button className='goBackButton' onClick={onGoBackClick}></button>
      </div>
    </div>
  );
}

export default Review;
