// React without WCAG/src/components/Auction.jsx
import { React, useState, useEffect } from 'react';
import {useParams} from "react-router-dom";
import Navbar from './Navbar';
import { getAuction, buyAuction } from "../api/AuctionAPI";
import './Auction.css';
import { getStorage } from "../utils/localStorage";

function Auction() {
  const { id } = useParams();
  const [auction, setAuction] = useState()
  const [startDate, setStartDate] = useState()
  const [endDate, setEndDate] = useState()

  useEffect(() => {
    async function loadAuction() {
      try {
        const auction = await getAuction(id);
        let startDate = new Date(auction.startDate);
        let endDate = new Date(auction.endDate);
        setStartDate(startDate.toLocaleString());
        setEndDate(endDate.toLocaleString());
        setAuction(auction);
      }
      catch { }
    }

    loadAuction();
  }, [id]);


  async function onBuyClick() {
    try {
      const buyParams = {
        AuctionID: id,
        UserID: getStorage("user").id
      }
      await buyAuction(buyParams);
      document.location.href = "/";
    } catch (e) { }
  }

  function onReviewClick() {
    document.location.href = "/review";
  }

  return (
    <div>
      <Navbar/>
      {auction && 
        <div className="auctionContainer">
          <p className="auctionTitle">{auction.title}</p>
          <div className="auctionImageComponent">
            <img className="auctionImg" alt={`Image of ${auction.title}`} alt={`Image of ${auction.title}`} src={auction.image}/>
            <p className="auctionDescription">{auction.description}</p>
          </div>
          <div className="auctionInformationComponent" >
            <div className="auctionSubFlexLeft" >
              <label className="auctionBasicLabel">Auction ends on:</label>
              <label className="auctionEndDate"><b>{endDate}</b></label>
              <br/>
              <label className="auctionBasicLabel">Auction created on:</label>
              <label className="auctionStartDate"><b>{startDate}</b></label>
              <button className="auctionReviewButton" onClick={onReviewClick}>Check opinion</button>
            </div>
            <div className="auctionSubFlexRight" >
              <div className="auctionPriceDiv">
                <label className="auctionBasicLabel">Auction price:</label>
                <label className="auctionPrice"><b>{auction.price} PLN</b></label>
              </div>
              <button className="auctionBuyButton" alt="Sell" onClick={onBuyClick}>Buy</button>
            </div>
          </div>
        </div>
      }
    </div>
  );
}

export default Auction;

// Angular without WCAG/src/components/auction/auction.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { AuctionAPIService } from '../../api/auction-api.service';
import { LocalService } from '../local.service';

@Component({
  selector: 'app-auction',
  templateUrl: './auction.component.html',
  styleUrls: ['./auction.component.css']
})
export class AuctionComponent implements OnInit {
  auction: any | undefined;
  id: any = ""
  startDate: any = ""
  endDate: any = ""

  constructor(
    private auctionAPIService: AuctionAPIService, 
    private router: Router, 
    private activatedRoute: ActivatedRoute,
    private localService: LocalService) { }

  ngOnInit(): void {
    try {
      this.id = this.activatedRoute.snapshot.paramMap.get('id');
      const auction = this.getAuctions();
      let startDate = new Date(this.auction.startDate);
      let endDate = new Date(this.auction.endDate);
      this.startDate = startDate.toLocaleString();
      this.endDate = endDate.toLocaleString();
      this.auction = auction;
    }
    catch { }
  }

  async getAuctions(): Promise<void> {
    this.auction = await this.auctionAPIService.getAuction(this.id);
  }

  async onBuyClick(): Promise<void> {
    const buyParams = {
      AuctionID: this.id,
      UserID: this.localService.getStorage("user").id
    }
    await this.auctionAPIService.buyAuction(buyParams);
    document.location.href = "/";
  }

  onReviewClick(): void {
    this.router.navigateByUrl("/review");
  }
}

<div>
  <div *ngIf="auction">  
    <div class="auctionContainer">
      <p class="auctionTitle">{{auction.title}}</p>
      <div class="auctionImageComponent">
        <img class="auctionImg" alt="Image of {{auction.title}}" alt="Image of {{auction.title}}" src="{{auction.image}}">
        <p class="auctionDescription">{{auction.description}}</p>
      </div>
      <div class="auctionInformationComponent" >
        <div class="auctionSubFlexLeft" >
          <label class="auctionBasicLabel">Auction ends on:</label>
          <label class="auctionEndDate"><b>{{endDate}}</b></label>
          <br/>
          <label class="auctionBasicLabel">Auction created on:</label>
          <label class="auctionStartDate"><b>{{startDate}}</b></label>
          <button class="auctionReviewButton" (click)="onReviewClick()">Check opinion</button>
        </div>
        <div class="auctionSubFlexRight" >
          <div class="auctionPriceDiv">
            <label class="auctionBasicLabel">Auction price:</label>
            <label class="auctionPrice"><b>{{auction.price}} PLN</b></label>
          </div>
          <button class="auctionBuyButton" alt="Sell" (click)="onBuyClick()">Buy</button>
        </div>
      </div>
    </div>
  </div>
</div>
