// React without WCAG/src/components/AuctionList.jsx
import {React, useState, useEffect} from 'react';
import {useParams} from "react-router-dom";
import Navbar from './Navbar';
import { getAuctionByCategory, getAuctionBySearch, getBoughtAuction } from "../api/AuctionAPI";
import './AuctionList.css';

function AuctionList() {
  const { category } = useParams();
  const { search } = useParams();
  const { id } = useParams();
  const [auctions, setAuctions] = useState();

  useEffect(() => {
    async function getAuctions() {
      try {
        let auctionList;
        if (category !== undefined)
          auctionList = await getAuctionByCategory(category);
        if (search !== undefined)
          auctionList = await getAuctionBySearch(search);
        if (id !== undefined)
          auctionList = await getBoughtAuction(id);

        setAuctions(auctionList);
      }
      catch { }
    }
    
    getAuctions();
  }, [category, search, id]);

  
  function auctionClick(props) {
    if(window.confirm("Do you want to be redirected to auction page?"))
      document.location.href = "/auction/" + props.id;
  }

  function closeAlert() {
    document.getElementById('alert').style.display='none';
  }

  function AuctionPanel(props) {
    const endDate = new Date(props.auction.endDate);
    return  <div className="auctionListPanel" onClick={() => auctionClick(props.auction)}>
              <div className="auctionListImageComponent">
                <img className="auctionListImg" src={props.auction.image}/>
                <label className="auctionListTitleLabel"><b>{props.auction.title}</b></label>
              </div>
              <div className="auctionListTextComponent" >
                <label><b>Price: {props.auction.price} PLN</b></label>
                <label><b>Ends on: {endDate.toLocaleString()}</b></label>
              </div>
            </div>
  }

  return (
    <div>
      <Navbar/>
        {auctions && auctions.map((auction) =>
          <div className="auctionListContainer">
            <span id='alert' className="auctionListAlert" onClick={closeAlert}>
              Number of auctions found: {auctions.length}.
            </span>
            <AuctionPanel key={auction.id} auction={auction}/>
          </div>
        )}
    </div>
  );
}

export default AuctionList;

// Angular without WCAG/src/components/auction-list/auction-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { AuctionAPIService } from '../../api/auction-api.service';

@Component({
  selector: 'app-auction-list',
  templateUrl: './auction-list.component.html',
  styleUrls: ['./auction-list.component.css']
})
export class AuctionListComponent implements OnInit {
  auctionList: any[] = [];

  constructor(private activatedRoute: ActivatedRoute, private auctionAPIService: AuctionAPIService) { }

  ngOnInit(): void {
    this.getAuctions();
  }

  async getAuctions(): Promise<void> {
    try{
      if (this.activatedRoute.snapshot.paramMap.get('category') != null) {
        this.auctionList = await this.auctionAPIService.getAuctionByCategory(this.activatedRoute.snapshot.paramMap.get('category'));
      }
      if (this.activatedRoute.snapshot.paramMap.get('search') != null) {
        this.auctionList = await this.auctionAPIService.getAuctionBySearch(this.activatedRoute.snapshot.paramMap.get('search'));
      }
      if (this.activatedRoute.snapshot.paramMap.get('id') != null)
      {
        this.auctionList = await this.auctionAPIService.getBoughtAuction(Number(this.activatedRoute.snapshot.paramMap.get('id')));
      }
    }
    catch{ }
  }

  auctionClick(props: any): void {
    if(window.confirm("Do you want to be redirected to auction page?"))
      document.location.href = "/auction/" + props.id;
  }

  closeAlert(): void {
    (document.getElementById('alert') as HTMLElement).style.display='none';
  }

  getAuctionDate(dateString: string): string {
    let date = new Date(dateString);
    return date.toLocaleString();
  }
}

<div>
  <div *ngIf="auctionList" class="auctionListContainer">
    <span id='alert' class="auctionListAlert" (click)="closeAlert()">
        Number of auctions found: {{auctionList.length}}.
    </span>
    <div *ngFor='let auction of auctionList' class="auctionListPanel" (click)="auctionClick(auction)">
      <div class="auctionListImageComponent">
        <img class="auctionListImg" src={{auction.image}}/>
        <label class="auctionListTitleLabel"><b>{{auction.title}}</b></label>
      </div>
      <div class="auctionListTextComponent" >
        <label><b>Price: {{auction.price}} PLN</b></label>
        <label><b>{{getAuctionDate(auction.endDate)}}</b></label>
      </div>
    </div>
  </div>
</div>
