// Angular with WCAG/src/components/auction-list/auction-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { LocalService } from '../local.service';
import { AuctionAPIService } from '../../api/auction-api.service';

@Component({
  selector: 'app-auction-list',
  templateUrl: './auction-list.component.html',
  styleUrls: ['./auction-list.component.css']
})
export class AuctionListComponent implements OnInit {
  category: string | null = null;
  search: string | null = null;
  id: number | null = null;
  auctionList: any[] = [];

  constructor(private localService: LocalService, private activatedRoute: ActivatedRoute, private auctionAPIService: AuctionAPIService) { }

  ngOnInit(): void {
    this.getAuctions();
  }

  async getAuctions(): Promise<void> {
    try{
      if (this.activatedRoute.snapshot.paramMap.get('category') != null) {
        this.category = this.activatedRoute.snapshot.paramMap.get('category');
        this.auctionList = await this.auctionAPIService.getAuctionByCategory(this.category);
        this.localService.setStorage("breadcrumbLink", `/category/${this.category}`);
        this.localService.setStorage("breadcrumbName", this.category);
      }
      if (this.activatedRoute.snapshot.paramMap.get('search') != null) {
        this.search = this.activatedRoute.snapshot.paramMap.get('search');
        this.auctionList = await this.auctionAPIService.getAuctionBySearch(this.search);
        this.localService.setStorage("breadcrumbLink", `/search/${this.search}`);
        this.localService.setStorage("breadcrumbName", this.search);
      }
      if (this.activatedRoute.snapshot.paramMap.get('id') != null)
      {
        this.id = Number(this.activatedRoute.snapshot.paramMap.get('id'));
        this.auctionList = await this.auctionAPIService.getBoughtAuction(this.id);
      }
    }
    catch{ }
  }

  auctionClick(props: any): void {
    if(this.localService.getStorage("notifications")){
      if(window.confirm("Do you want to be redirected to auction page?")){
        document.location.href = "/auction/" + props.id;
      }
    }
    else{
      document.location.href = "/auction/" + props.id;
    }
  }

  closeAlert(): void {
    (document.getElementById('alert') as HTMLElement).style.display='none';
  }

  getAuctionDate(dateString: string): string {
    let date = new Date(dateString);
    return date.toLocaleString();
  }
}

<div>
  <div *ngIf="auctionList" class="auctionListContainer">
    <title class='title' hidden={{true}}>Auction list</title>
    <span id='alert' class="auctionListAlert" attr.aria-label="Number of auctions found: {{auctionList.length}}" (click)="closeAlert()">
        Number of auctions found: {{auctionList.length}}.
    </span>
    <div *ngFor='let auction of auctionList' class="auctionListPanel" (click)="auctionClick(auction)">
      <div class="auctionListImageComponent">
        <img class="auctionListImg" alt="{{auction.name}}" src={{auction.image}}/>
        <label class="auctionListTitleLabel"><b>{{auction.title}}</b></label>
      </div>
      <div class="auctionListTextComponent" >
        <label aria><b>Price: {{auction.price}} PLN</b></label>
        <label><b>{{getAuctionDate(auction.endDate)}}</b></label>
      </div>
    </div>
  </div>
</div>

// React with WCAG/src/components/AuctionList.jsx
import {React, useState, useEffect} from 'react';
import {useParams} from "react-router-dom";
import Navbar from './Navbar';
import { getAuctionByCategory, getAuctionBySearch, getBoughtAuction } from "../api/AuctionAPI";
import './AuctionList.css';
import { getStorage, setStorage } from "../utils/localStorage";

function AuctionList() {
  const { category } = useParams();
  const { search } = useParams();
  const { id } = useParams();
  const [auctions, setAuctions] = useState();

  useEffect(() => {
    async function getAuctions() {
      try {
        let auctionList;
        if (category !== undefined) {
          auctionList = await getAuctionByCategory(category);
          setStorage("breadcrumbLink", `/category/${category}`);
          setStorage("breadcrumbName", category);
        }
        if (search !== undefined) {
          auctionList = await getAuctionBySearch(search);
          setStorage("breadcrumbLink", `/search/${search}`);
          setStorage("breadcrumbName", search);
        }
        if (id !== undefined)
          auctionList = await getBoughtAuction(id);

        setAuctions(auctionList);
      }
      catch { }
    }
    
    getAuctions();
  }, [category, search, id]);
  
  function auctionClick(props) {
    if(getStorage("notifications")){
      if(window.confirm("Do you want to be redirected to auction page?")){
        document.location.href = "/auction/" + props.id;
      }
    }
    else{
      document.location.href = "/auction/" + props.id;
    }
  }

  function closeAlert() {
    document.getElementById('alert').style.display='none';
  }

  function AuctionPanel(props) {
    const endDate = new Date(props.auction.endDate);
    return  <div className="auctionListPanel" onClick={() => auctionClick(props.auction)}>
              <div className="auctionListImageComponent">
                <img className="auctionListImg" alt={`${props.name}`} src={props.auction.image}/>
                <label className="auctionListTitleLabel"><b>{props.auction.title}</b></label>
              </div>
              <div className="auctionListTextComponent" >
                <label aria><b>Price: {props.auction.price} PLN</b></label>
                <label><b>Ends on: {endDate.toLocaleString()}</b></label>
              </div>
            </div>
  }

  return (
    <div>
      <Navbar/>
      <title class='title' hidden={true}>Auction list</title>
      {auctions && auctions.map((auction) =>
        <div className="auctionListContainer">
          <span id='alert' className="auctionListAlert" aria-label={`Number of auctions found: ${auctions.length}`} onClick={closeAlert}>
            Number of auctions found: {auctions.length}.
          </span>
          <AuctionPanel key={auction.id} auction={auction}/>
        </div>
      )}
    </div>
  );
}

export default AuctionList;
