// Angular with WCAG/src/components/create-auction/create-auction.component.ts
import { Component, OnInit } from '@angular/core';
import { LocalService } from '../local.service';
import { AuctionAPIService } from '../../api/auction-api.service';

@Component({
  selector: 'app-create-auction',
  templateUrl: './create-auction.component.html',
  styleUrls: ['./create-auction.component.css']
})
export class CreateAuctionComponent implements OnInit {
  email: string = "";
  title: string = "";
  description: string = "";
  price: number = 0;
  quantity: number = 1;
  date: Date | undefined;
  image: string | undefined;
  selectedCategory: string = "Cars";
  selectedSubCategory: string = "";
  isLoading: boolean = false;
  createError: string = "";
  categoriesList = this.localService.getStorage("categories");
  masterCategoriesList: any[] = [];
  subSubCategoriesList: any[] = [];

  constructor(private localService: LocalService, private auctionAPIService: AuctionAPIService) { }

  ngOnInit(): void {
    this.categoriesList = this.localService.getStorage("categories");
    this.masterCategoriesList = this.categoriesList.filter((category : any) => category.masterId == null);
  }

  async onCreateClicked(): Promise<void> {
    try {
      this.isLoading = true;
      this.createError = "";
      let auctionCategory = this.selectedSubCategory === "" ? this.selectedCategory : this.selectedSubCategory;
      const startDate = new Date().toJSON();
      const auctionParams = {
        Title: this.title,
        Description: this.description,
        Price: this.price,
        Quantity: this.quantity,
        StartDate: startDate,
        EndDate: this.date,
        CategoryName: auctionCategory,
        Image: this.image,
        UserID: this.localService.getStorage("user").id
      };
      await this.auctionAPIService.addAuction(auctionParams);    
      document.location.href = "/";
    } catch {
      this.createError = "Error occurred, try again.";
    } finally {
      this.isLoading = false;
    }
  }

  onImageChanged(event : any): void {
    const fileList = event.target.files;
    this.imageToBase64(fileList[0]);
  }

  imageToBase64(file : any): void {
    var reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = (e) => {
      this.image = reader.result?.toString();
    }
    reader.onerror = function (error) {
      console.log('Error: ', error);
    };
  }
  
  getSubCategories(id: number) {
    return this.categoriesList.filter((subCategory: any) => subCategory.masterId === id);
  }

  onSelectOptionChanged(event: any) {
    this.selectedSubCategory = "";
    this.selectedCategory = event.target.value;
    let currentlySelectedCategoryId = this.categoriesList.find((category: any) => category.name == this.selectedCategory).id;
    this.subSubCategoriesList = this.categoriesList.filter((category: any) => category.masterId == currentlySelectedCategoryId);
  }

  onSubCategoryChanged(event: any) {
    this.selectedSubCategory = event.target.value;
    this.title = "";
  }
}

<div>
  <form (ngSubmit)='onCreateClicked()' ngNativeValidate>
    <div class='createContainer'>
      <title class='title'>Create auction</title>
      <label class='createLabel' for="title"><b>Title:</b></label>
      <input class='createInput' id="title" type="text" [(ngModel)]="title" placeholder='Auction title' required />
      <label class='createLabel' for="description"><b>Description:</b></label>
      <textarea class="createTextArea" id="description" [(ngModel)]="description" rows="10" placeholder='Add auction description' required></textarea>
      <label class='createLabel' for="price"><b>Price for one item:</b></label>
      <input class='createInput' id="price" [(ngModel)]="price" type="number" step="0.01" min="1" placeholder='Set price' required />
      <label class='createLabel' for="rangeInput"><b>Quantity:</b></label>
      <input class='createRangeInput' name="quantity" [(ngModel)]="quantity" id="rangeInput" type="range" min="1" max="40"/>
      <output id="rangeOutput">{{quantity}}</output>
      <label class='createLabel' for="date"><b>Auction end date and time:</b></label>
      <input class='createInput' id="date" [(ngModel)]="date" type="datetime-local" required />
      <label class='createLabel'><b>Select category:</b></label>
      <div *ngIf="categoriesList" class='createInput'>
        <select class="createSelect" (change)='onSelectOptionChanged($event)'>
          <optgroup *ngFor='let masterCategory of masterCategoriesList' label="{{masterCategory.name}}">
            <option *ngFor="let subCategory of getSubCategories(masterCategory.id)">{{subCategory.name}}</option>
          </optgroup>
        </select>
      </div>
      <div *ngIf="subSubCategoriesList" class='createInput'>
        <div *ngFor='let subSubCategory of subSubCategoriesList' class='createLabel'>
          <input type="radio" id="subcategoryRadio" class='createLabel' value={{subSubCategory.name}} (change)='onSubCategoryChanged($event)' required />
          <label for="subcategoryRadio"><b>{{subSubCategory.name}}</b></label>
        </div>
      </div>
      <div class='flexRow'>
        <label class='createPictureLabel' for="fileInput"><b>Auction picture:</b></label>
        <div class='createHiddenDiv'>Add only one picture</div>
      </div>
      <input class='createInput' type="file" id="fileInput" (change)='onImageChanged($event)' required />
      <input class='createSubmit' type="submit" value="Submit" alt="Submit" />
      <p *ngIf="isLoading">Creating auction....</p>
      <p *ngIf="createError != ''">{{createError}}</p>
    </div>
  </form>
</div>

// React with WCAG/src/components/CreateAuction.jsx
import {React, useState, useEffect} from 'react';
import Navbar from '../components/Navbar'
import { getStorage } from "../utils/localStorage";
import './CreateAuction.css';
import { addAuction } from "../api/AuctionAPI";

function CreateAuction() {
  const [categoriesList, setcategoriesList] = useState();
  const [title, setTitle] = useState();
  const [description, setDescription] = useState();
  const [price, setPrice] = useState();
  const [quantity, setQuantity] = useState();
  const [date, setDate] = useState();
  const [image, setImage] = useState();
  const [selectedCategory, setSelectedCategory] = useState("Cars");
  const [selectedSubCategory, setSelectedSubCategory] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [createError, setCreateError] = useState('');

  useEffect(() => {
    try {
      document.getElementById('rangeInput').value = 1;
      setcategoriesList(getStorage("categories"));
    } catch { }
  }, []);

  function onSelectOptionChanged(event) {
    setSelectedSubCategory("");
    setSelectedCategory(event.target.value);
  }

  function onSubCategoryChanged(event) {
    setSelectedSubCategory(event.target.value);
  }

  function onTitleChanged(event) {
    setTitle(event.target.value);
  }

  function onDescriptionChanged(event) {
    setDescription(event.target.value);
  }

  function onPriceChanged(event) {
    setPrice(event.target.value);
  }

  function onDateChanged(event) {
    setDate(event.target.value);
  }

  function onImageChanged(event) {
    const fileList = event.target.files;
    imageToBase64(fileList[0]);
  }

  function imageToBase64(file) {
    var reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = function () {
      setImage(reader.result);
    };
    reader.onerror = function (error) {
      console.log('Error: ', error);
    };
  }

  async function onCreateClicked(e) {
    e.preventDefault();
    setIsLoading(true);
    setCreateError('');
    try {
      let auctionCategory = selectedSubCategory === "" ? selectedCategory : selectedSubCategory;
      const startDate = new Date().toJSON();
      const auctionParams = {
        Title: title,
        Description: description,
        Price: price,
        Quantity: quantity,
        StartDate: startDate,
        EndDate: date,
        CategoryName: auctionCategory,
        Image: image,
        UserID: getStorage("user").id
      };
      await addAuction(auctionParams);
      document.location.href = "/";
    } catch (e) {
      console.error(e, e.stack);
      setCreateError("Error occurred, try again");
    } finally {
      setIsLoading(false);
    }
  }

  function SelectorItem() {
    return <select className="createSelect" onChange={onSelectOptionChanged} value={selectedCategory}>
      {categoriesList.filter(category => category.masterId == null).map((filteredCategory) => <optgroup key={filteredCategory.name} label={filteredCategory.name}>
        {categoriesList.filter(subCategory => subCategory.masterId === filteredCategory.id).map((filteredSubCategory) => <option key={filteredSubCategory.name} value={filteredSubCategory.name}>{filteredSubCategory.name}</option>
        )}
      </optgroup>
      )}
    </select>;
  }

  function SubCategoryRadioButtons() {
    const currentlySelectedCategoryId = categoriesList.find(category => category.name === selectedCategory).id;
    return categoriesList.filter(category => category.masterId === currentlySelectedCategoryId).map((filteredCategory) => <div className='createLabel' key={filteredCategory.name}>
      <input type="radio" key={filteredCategory.name} id="subcategoryRadio" value={filteredCategory.name}
        onChange={onSubCategoryChanged} checked={selectedSubCategory === filteredCategory.name} required />
      <label htmlFor="subcategoryRadio" className='createLabel'><b>{filteredCategory.name}</b></label>
    </div>
    );
  }

  function onRangeInput() {
    let quantityValue = document.getElementById('rangeInput').value;
    document.getElementById('rangeOutput').value = quantityValue;
    setQuantity(quantityValue);
  }

  return (
    <div>
      <Navbar />
      <form onSubmit={onCreateClicked}>
        <div className='createContainer'>
          <title className='title'>Create auction</title>
          <label className='createLabel' htmlFor="title"><b>Title:</b></label>
          <input className='createInput' id="title" type="text" placeholder='Auction title' onChange={onTitleChanged} required />
          <label className='createLabel' htmlFor="description"><b>Description:</b></label>
          <textarea className="createTextArea" id="description" rows="10" placeholder='Add auction description' onChange={onDescriptionChanged} required />
          <label className='createLabel' htmlFor="price"><b>Price for one item:</b></label>
          <input className='createInput' id="price" type="number" step="0.01" min="1" placeholder='Set price' onChange={onPriceChanged} required />
          <label className='createLabel' htmlFor="rangeInput"><b>Quantity:</b></label>
          <input className='createRangeInput' id="rangeInput" type="range" min="1" max="40" onInput={onRangeInput} />
          <output id="rangeOutput">1</output>
          <label className='createLabel' htmlFor="date"><b>Auction end date and time:</b></label>
          <input className='createInput' id="date" type="datetime-local" onChange={onDateChanged} required />
          <label className='createLabel'><b>Select category:</b></label>
          {categoriesList && <SelectorItem />}
          {categoriesList && <SubCategoryRadioButtons />}
          <div className='flexRow'>
            <label htmlFor="fileInput" className='createPictureLabel'><b>Auction picture:</b></label>
            <div className='createHiddenDiv'>Add only one picture</div>
          </div>
          <input className='createInput' type="file" id="fileInput" onChange={onImageChanged} required />
          <input className='createSubmit' type="submit" value="Submit" alt="Submit" />
          {isLoading && <p>Creating auction....</p>}
          {createError && <p>{createError}</p>}
        </div>
      </form>
    </div>
  );
}

export default CreateAuction;
