// Angular with WCAG/src/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { LocalService } from '../local.service';
import { CategoryAPIService } from '../../api/category-api.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  notificationsStatus: string = this.localService.getStorage("notifications") == true ? "Site notifications currently enabled" : "Site notifications currently disabled";
  categoriesList: any[] = [];
  mainCategoriesList: any[] = [];
  subCategoriesList: any[] = [];
  subSubCategoriesList: any[] = [];
  isMainCategorySelected: boolean = false;
  mainCategorySelected: number | undefined;
  isSubCategorySelected: boolean = false;
  isLoading: boolean = false;
  registerError: string = "";

  constructor(private localService: LocalService, private categoryAPIService: CategoryAPIService) { }

  ngOnInit(): void {
    try{
      let categoriesList = this.localService.getStorage("categories");
      if (categoriesList === false) {
        this.getCategories();
        categoriesList = this.localService.getStorage("categories");
      }
      this.categoriesList = categoriesList;
      this.mainCategoriesList = this.categoriesList.filter(category => category.isSub === false);
    }
    catch{}
  }

  async getCategories(): Promise<void> {
    try {
      this.isLoading = true;
      const categoriesList = await this.categoryAPIService.getCategory();
      this.localService.setStorage("categories", categoriesList);
    }
    catch { }
    finally {
      this.isLoading = false;
    }
  }

  mainCategoryClick(mainCategoryId: number): void {
    this.isSubCategorySelected = false;
    this.mainCategorySelected = mainCategoryId;
    this.isMainCategorySelected = true;
    this.subCategoriesList = this.categoriesList.filter(category => category.masterId === this.mainCategorySelected);
  }

  subCategoryClick(props: any): void {
    this.isSubCategorySelected = true;
    this.subSubCategoriesList = this.categoriesList.filter(category => category.masterId === props.id);
    if (this.subSubCategoriesList.length === 0)
      this.goToCategory(props.name);
  }

  goToCategory(categoryName: string): void {
    document.location.href = "/category/" + categoryName;
  }

  handleAnimation(): void {
    if ((document.getElementById('homeLabel') as HTMLElement).style.animationIterationCount === '0')
      (document.getElementById('homeLabel') as HTMLElement).style.animationIterationCount = 'infinite';
    else
      (document.getElementById('homeLabel') as HTMLElement).style.animationIterationCount = '0';
  }

  onNotificationClick(): void {
    if (this.localService.getStorage("notifications") == true) {
      this.localService.setStorage("notifications", false);
      this.notificationsStatus = "Site notifications currently disabled";
    }
    else {
      this.localService.setStorage("notifications", true);
      this.notificationsStatus = "Site notifications currently enabled";
    }
  }
}

<div>
  <div>
    <div *ngIf="categoriesList">
      <title class='title' hidden={{true}}>Home</title>      
      <button id="animationButton" (click)="onNotificationClick()" attr.alt="{{notificationsStatus}}">{{notificationsStatus}}</button>
      <button id="animationButton" (click)="handleAnimation()" alt="Toggle animation">Toggle animation</button>
      <label id="homeLabel" class="homeLabel"><b>What are you buying today?</b></label>
      <div class="homeMainContainer">
        <div *ngFor='let mainCategory of mainCategoriesList'>
          <div class="homeFlexElement" (click)="mainCategoryClick(mainCategory.id)">
            <input class="mainCategoryInput" alt="Image of {{mainCategory.name}}" src="assets/{{mainCategory.name}}.jpg" type="image" />
            <p><b>{{mainCategory.name}}</b></p>
          </div>
        </div>
      </div>
    </div>
    <div *ngIf="isMainCategorySelected">
      <div class="homeSubContainer">
        <div *ngFor='let subCategory of subCategoriesList'>
          <div class="homeFlexElement" (click)="subCategoryClick(subCategory)">
            <input class="subCategoryInput" alt="Image of {{subCategory.name}}" src="assets/{{subCategory.name}}.jpg" type="image" />
            <p><b>{{subCategory.name}}</b></p>
          </div>
        </div>
      </div>
    </div>
      <div *ngIf="isSubCategorySelected">
        <div class="homeSubContainer">
          <div *ngFor='let subSubCategory of subSubCategoriesList'>
            <div class="homeFlexElement" (click)="goToCategory(subSubCategory.name)">
              <input class="subSubCategoryInput" alt="Image of {{subSubCategory.name}}" src="assets/{{subSubCategory.name}}.jpg" type="image" />
              <p><b>{{subSubCategory.name}}</b></p>
            </div>
          </div>
        </div>
      </div>  
    <b *ngIf="isLoading">Loading....</b>
  </div>
</div>

// React with WCAG/src/components/Home.jsx
import {React, useState, useEffect} from 'react';
import Navbar from '../components/Navbar'
import { getStorage, setStorage } from "../utils/localStorage";
import './Home.css';
import { getCategory } from "../api/CategoryAPI";

function Home() {
  const [categoriesList, setcategoriesList] = useState();
  const [isMainCategorySelected, setIsMainCategorySelected] = useState(false);
  const [mainCategorySelected, setMainCategorySelected] = useState();
  const [isSubCategorySelected, setIsSubCategorySelected] = useState(false);
  const [subCategorySelected, setSubCategorySelected] = useState();
  const [isLoading, setIsLoading] = useState(false);
  const [notificationsStatus, setNotifications] = useState(getStorage("notifications") ? "Site notifications currently enabled" : "Site notifications currently disabled");

  useEffect(() => {
    try {
      let categoriesList = getStorage("categories");
      if (categoriesList === false) {
        getCategories();
        categoriesList = getStorage("categories");
      }
      setcategoriesList(categoriesList);
    } catch { }
  }, []);

  async function getCategories() {
    try {
      setIsLoading(true);
      const categoriesList = await getCategory();
      setStorage("categories", categoriesList);
    }
    catch { }
    finally {
      setIsLoading(false);
    }
  }

  function mainCategoryClick(mainCategoryId) {
    setIsSubCategorySelected(false);
    setMainCategorySelected(mainCategoryId);
    setIsMainCategorySelected(true);
  }

  function subCategoryClick(props) {
    if (categoriesList.filter(category => category.masterId === props.subCategoryId).length === 0)
      goToCategory(props.name);
    setIsSubCategorySelected(false);
    setSubCategorySelected(props.subCategoryId);
    setIsSubCategorySelected(true);
  }

  function goToCategory(categoryName) {
    document.location.href = "/category/" + categoryName;
  }

  function HomeMenu() {
    return <div>
      <title class='title' hidden={true}>Home</title>
      <button id="animationButton" onClick={onNotificationClick} alt={notificationsStatus}>{notificationsStatus}</button>
      <button id="animationButton" onClick={handleAnimation} alt="Toggle animation">Toggle animation</button>
      <label id="homeLabel" className="homeLabel"><b>What are you buying today?</b></label>
      <div className="homeMainContainer">
        {categoriesList.filter(category => category.isSub === false).map((filteredCategory) => <MainContainerItem key={filteredCategory.name} name={filteredCategory.name} mainCategoryId={filteredCategory.id} />
        )}
      </div>
    </div>;
  }

  function SubMenu() {
    return <div className="homeSubContainer">
      {categoriesList.filter(category => category.masterId === mainCategorySelected).map((filteredCategory) => <SubContainerItem key={filteredCategory.name} name={filteredCategory.name} subCategoryId={filteredCategory.id} />
      )}
    </div>;
  }

  function SubSubMenu() {
    return <div className="homeSubContainer">
      {categoriesList.filter(category => category.masterId === subCategorySelected).map((filteredCategory) => <SubSubContainerItem key={filteredCategory.name} name={filteredCategory.name} subCategoryId={filteredCategory.id} />
      )}
    </div>;
  }

  function MainContainerItem(props) {
    const fileNameExt = props.name + '.jpg';
    return <div className="homeFlexElement" onClick={() => mainCategoryClick(props.mainCategoryId)} onDoubleClick={() => goToCategory(props.name)}>
      <input className="mainCategoryInput" alt={`Image of ${props.name}`} src={require('../img/' + fileNameExt)} type="image" />
      <p><b>{props.name}</b></p>
    </div>;
  }

  function SubContainerItem(props) {
    const fileNameExt = props.name + '.jpg';
    return <div className="homeFlexElement" onClick={() => subCategoryClick(props)} onDoubleClick={() => goToCategory(props.name)}>
      <input className="subCategoryInput" alt={`Image of ${props.name}`} src={require('../img/' + fileNameExt)} type="image" />
      <p><b>{props.name}</b></p>
    </div>;
  }

  function SubSubContainerItem(props) {
    const fileNameExt = props.name + '.jpg';
    return <div className="homeFlexElement" onClick={() => goToCategory(props.name)}>
      <input className="subSubCategoryInput" alt={`Image of ${props.name}`} src={require('../img/' + fileNameExt)} type="image" />
      <p><b>{props.name}</b></p>
    </div>;
  }

  function handleAnimation() {
    if (document.getElementById('homeLabel').style.animationIterationCount === '0')
      document.getElementById('homeLabel').style = 'animation-iteration-count: infinite;';

    else
      document.getElementById('homeLabel').style = 'animation-iteration-count: 0;';
  }

  async function onNotificationClick(e) {
    e.preventDefault();
    if (getStorage("notifications")) {
      setStorage("notifications", false);
      setNotifications("Site notifications currently disabled");
    }
    else {
      setStorage("notifications", true);
      setNotifications("Site notifications currently enabled");
    }
  }

  return (
    <div>
      <Navbar />
      <div>
        {categoriesList && <HomeMenu />}
        {isMainCategorySelected && <SubMenu />}
        {isSubCategorySelected && <SubSubMenu />}
        {isLoading && <b>Loading....</b>}
      </div>
    </div>
  );
}

export default Home;
