// Angular with WCAG/src/components/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { LocalService } from '../local.service';
import { UserAPIService } from '../../api/user-api.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  username: string = "";
  password: string = "";
  isLoading: boolean = false;
  registerError: string = "";
  checkboxState: boolean = false;

  constructor(private localService: LocalService, private userAPIService: UserAPIService) { }

  ngOnInit(): void {
  }

  async onLoginClicked(): Promise<void> {
    try {
      this.isLoading = true;
      this.registerError = "";
      if (this.username == "" || this.password == "") {
        this.registerError = "No username or password";
        return;
      }
      
      const loginParams = {
        Login: this.username,
        Password: this.password
      };
      const userParameters = await this.userAPIService.userLogin(loginParams);
      this.localService.setStorage("user", userParameters);      
      document.location.href = "/";
    } catch {
      this.registerError = "Wrong username or password";
    } finally {
      this.isLoading = false;
    }
  }
}

<div>
  <form class='loginContainer' (ngSubmit)='onLoginClicked()' ngNativeValidate>
    <title class='title'>Login</title>
    <label class='loginLabel' for="loginUsername"><b>Username:</b></label>
    <input class='loginInput' id="loginUsername" [(ngModel)]="username" placeholder='username' type="text" ngModel required />
    <label class='loginLabel' for="loginPassword"><b>Password:</b></label>
    <input class='loginInput' id="loginPassword" [(ngModel)]="password" placeholder='password' type="password" required />
    <input class='loginSubmit' type="submit" value="Submit" alt="Submit" />
    <a class='loginHyperlink' href="/register">Click to create account</a>
    <p *ngIf="isLoading">Logging user....</p>
    <p *ngIf="registerError != ''">{{registerError}}</p>
  </form>
</div>

// React with WCAG/src/components/Login.jsx
import {React, useState} from "react";
import Navbar from '../components/Navbar';
import { userLogin } from "../api/UserAPI";
import './Login.css';
import { setStorage } from "../utils/localStorage";

function Login() {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [loginError, setLoginError] = useState('');

  async function onLoginClicked(e) {
    e.preventDefault();
    if (!username || !password) {
      setLoginError("No username or password");
      return;
    }
    setIsLoading(true);
    setLoginError('');
    try {
      const loginParams = {
        Login: username,
        Password: password
      };
      const userParameters = await userLogin(loginParams);
      setStorage("user", userParameters);
      document.location.href = "/";
    } catch {
      setLoginError("Wrong username or password");
    } finally {
      setIsLoading(false);
    }
  }

  function onUsernameChanged(event) {
    setUsername(event.target.value);
  }

  function onPasswordChanged(event) {
    setPassword(event.target.value);
  }

  return (
    <div>
      <Navbar />
      <form className='loginContainer' onSubmit={onLoginClicked}>
        <title className='title'>Login</title>
        <label className='loginLabel' htmlFor="loginUsername"><b>Username:</b></label>
        <input className='loginInput' id="loginUsername" placeholder='username' type="text" onChange={onUsernameChanged} required />
        <label className='loginLabel' htmlFor="loginPassword"><b>Password:</b></label>
        <input className='loginInput' id="loginPassword" placeholder='password' type="password" onChange={onPasswordChanged} required />
        <input className='loginSubmit' type="submit" value="Submit" alt="Submit" />
        <a className='loginHyperlink' href="/register">Click to create account</a>
        {isLoading && <p>Logging in....</p>}
        {loginError && <p>{loginError}</p>}
      </form>
    </div>
  );
}

export default Login;
