// Vue with WCAG/src/components/TermsExtended.vue
<template>
<TermsComponent indexing='extended'></TermsComponent>
<section id="extendedSection">
  <title>Extended Section</title>
  <p>These are the T&C governing the use of this Service and the agreement that operates between You and the Company. These T&C set out the rights and obligations of all users regarding the use of the Service.</p>
  <p>Your access to and use of the Service is conditioned on Your acceptance of and compliance with these T&C. These T&C apply to all visitors, users and others who access or use the Service.</p>
  <p>By accessing or using the Service You agree to be bound by these T&C. If You disagree with any part of these T&C then You may not access the Service.</p>
  <p>You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service.</p>
  <p>We reserve right to change Your username if it contains vulgar word or onomatopoeia.</p>
</section>
</template>

<script>
import TermsComponent from './Terms'

export default {
  name: 'TermsExtendedComponent',
  components: {
    TermsComponent
  }
}
</script>

<style scoped>

</style>

// React with WCAG/src/components/TermsExtended.jsx
import {React} from 'react';
import Terms from './Terms'

function TermsExtended() {
  return (
    <div>
      <Terms indexing='extended' />
      <section id="extendedSection">
        <title>Extended Section</title>
        <p>These are the T&C governing the use of this Service and the agreement that operates between You and the Company. These T&C set out the rights and obligations of all users regarding the use of the Service.</p>
        <p>Your access to and use of the Service is conditioned on Your acceptance of and compliance with these T&C. These T&C apply to all visitors, users and others who access or use the Service.</p>
        <p>By accessing or using the Service You agree to be bound by these T&C. If You disagree with any part of these T&C then You may not access the Service.</p>
        <p>You represent that you are over the age of 18. The Company does not permit those under 18 to use the Service.</p>
        <p>We reserve right to change Your username if it contains vulgar word or onomatopoeia.</p>
      </section>
    </div>
  );
}

export default TermsExtended;
