// Vue without WCAG/src/components/Navbar.vue
<template>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Shop</a>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{usernameHello}}</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li v-if="!isLoggedIn" class="nav-item">
              <a class="dropdown-item" href="/login">Login</a>
            </li>
            <li v-if="!isLoggedIn" class="nav-item">
              <a class="dropdown-item" href="/register">Register</a>
            </li>
            <li v-if="isLoggedIn" class="nav-item">
              <a class="dropdown-item" href="/create">Create auction</a>
            </li>
            <li v-if="isLoggedIn" class="nav-item">
              <a class="dropdown-item" href="{{sellingLink}}">Bought auctions</a>
            </li>
            <li v-if="isLoggedIn" class="nav-item">
              <a class="dropdown-item" href="javascript:void(0)" @click="onLogoutClick">Logout</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
</template>

<script>
import { getStorage, setStorage } from '../utils/localStorage'

export default {
  name: 'NavbarComponent',
  data() {
    return { 
      isLoggedIn: (getStorage("user") == false) ? false : true,
      usernameHello: (getStorage("user") == false) ? "Account" : `Hello, ${getStorage("user")?.login}`,
      sellingLink: `/bought/${getStorage("user")?.id}`,
      searchInput: "",
    }
  },

  methods: {  
    onLogoutClick() {
      setStorage("user", false);
      document.location.href = "/";
    }, 
  }
}
</script>

<style scoped>

</style>

// Angular without WCAG/src/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { LocalService } from '../local.service';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class HeroesComponent implements OnInit {
  isLoggedIn: boolean = (this.localService.getStorage("user") == false) ? false : true;
  usernameHello: string = "Hello, " + this.localService.getStorage("user").login;
  sellingLink: string = "/bought/" + this.localService.getStorage("user").id;
  searchInput: string = "";

  constructor(private localService: LocalService) { }

  ngOnInit(): void {
  }

  onLogoutClick(): void {
    this.localService.setStorage("user", false);
    document.location.href = "/";
  }
}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Shop</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li *ngIf="!isLoggedIn" class="nav-item">
          <a class="nav-link" href="/login">Login</a>
        </li>
        <li *ngIf="!isLoggedIn" class="nav-item">
          <a class="nav-link" href="/register">Register</a>
        </li>
        <li *ngIf="isLoggedIn" class="nav-item">
          <a class="nav-link" href="/create">Create auction</a>
        </li>
        <li *ngIf="isLoggedIn" class="nav-item">
          <a class="nav-link" href="{{sellingLink}}">Bought auctions</a>
        </li>
        <li *ngIf="isLoggedIn" class="nav-item">
          <a class="nav-link" href="javascript:void(0)" (click)="onLogoutClick()">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
